<?php
/**
 * @file
 * Drupal database deploy module
 *
 * Make deployment via git much easier.
 */
 
/**
 * Implements hook_node_update().
 */
function drupal_deploy_node_update($node) {
  $op = 'node_update';
  drupal_deploy_save_transaction('node', $op, $node);
}

/**
 * Implements hook_node_insert().
 */
function drupal_deploy_node_insert($node) {
  $op = 'node_insert';
  drupal_deploy_save_transaction('node', $op, $node);
}

/**
 * Implements hook_node_delete().
 */
function drupal_deploy_node_delete($node) {
  $op = 'node_delete';
  drupal_deploy_save_transaction('node', $op, $node);
}

/**
 * Implements hook_node_revision_delete().
 */
function drupal_deploy_node_revision_delete($node) {
  $op = 'node_revision_delete';
  drupal_deploy_save_transaction('node', $op, $node);
}

/**
 *
 */
function drupal_deploy_save_transaction($type, $op, $store) {
  $root_dir = variable_get('drupal_deploy_path_to_transations', 'private://drupal_deploy/');

  $type_dir = $root_dir . '/' . $type;

  file_check_directory($type_dir, FILE_CREATE_DIRECTORY);

  $transaction_file = $type_dir . DIRECTORY_SEPARATOR . microtime(TRUE) * 10000;

  $data = array(
    'op' => $op,
    'data' => $store,
  );
  file_unmanaged_save_data(serialize($data), $transaction_file);
}

function drupal_deploy_export_pretty_json($json) {
  $result      = '';
  $pos         = 0;
  $strLen      = strlen($json);
  $indentStr   = '  ';
  $newLine     = "\n";
  $prevChar    = '';
  $outOfQuotes = true;

  for ($i=0; $i<=$strLen; $i++) {
    $char = $json[$i];
    
    if ($char == '"' && $prevChar != '\\') 
    {
      $outOfQuotes = !$outOfQuotes;
    }
    else if(($char == '}' || $char == ']') && $outOfQuotes)
    {
      $result .= $newLine;
      $pos --;
      for ($j = 0; $j < $pos; $j++) {
        $result .= $indentStr;
      }
    }

    $result .= $char;

    if (($char == ',' || $char == '{' || $char == '[') && $outOfQuotes)
    {
      $result .= $newLine;
      if ($char == '{' || $char == '[') {
        $pos ++;
      }

      for ($j = 0; $j < $pos; $j++) {
        $result .= $indentStr;
      }
    }

    $prevChar = $char;
  }

  return $result;
}

function drupal_deploy_export_save($items, $filename = ''){
  $data = json_encode($items);
  $data = drupal_deploy_export_pretty_json($data);
  if(file_put_contents($filename, $data)){
    drupal_set_message(t('Exported to file !filename', array('!filename' => $filename)));
  }
}
